# Generated by Django 4.1.3 on 2022-11-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='Tag',
        ),
        migrations.AddField(
            model_name='todo',
            name='Tag',
            field=models.ManyToManyField(blank=True, null=True, to='app.tag'),
        ),
    ]
